

function CVPreview({person}){
    return(
        <>
        <div>
            <h1>{person.name}</h1>
        </div>
        <div>
            <h2>{person.headline}</h2>
        </div>
        <div>
            <h1>{person.email}</h1>
        </div>
        <div>
            <h2>{person.portfolio}</h2>
        </div>
        <div>
            <h1>{person.github}</h1>
        </div>
        <div>
            <h2>{person.linkedin}</h2>
        </div>
        <div>
            <h1>{person.title}</h1>
        </div>
        <div>
            <h2>{person.companyName}</h2>
        </div>
        <div>
            <h1>{person.location}</h1>
        </div>
        <div>
            <h2>{person.startDate}</h2>
        </div>
        <div>
            <h2>{person.endDate}</h2>
        </div>
        <div>
            <h1>{person.skills}</h1>
        </div>
        <div>
            <h1>{person.school}</h1>
        </div>
        <div>
            <h2>{person.degree}</h2>
        </div>
        <div>
            <h2>{person.endShoolDate}</h2>
        </div>
        <div>
            <h1>{person.grade}</h1>
        </div>
        <div>
            <h1>{person.project}</h1>
        </div>
        <div>
            <h2>{person.description}</h2>
        </div>
        <div>
            <h2>{person.media}</h2>
        </div>
        </>
    )
}

export default CVPreview;